dataset: data/raw.csv
preprocessing:
  scale: True
  encode: False
model:
  type: RandomForest
  params:
    n_estimators: [100, 200, 300]
    max_depth: [5, 7, 10]
    random_state: 42
training:
  test_size: 0.2
  random_state: 42
target_column: Species
